//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:2.0.50727.5420
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace WorkStudioLibrary.Resources {
    using System;
    
    
    /// <summary>
    ///   强类型资源类，用于查找本地化字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "2.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("WorkStudioLibrary.Resources.Resource", typeof(Resource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   为使用此强类型资源类的所有资源查找
        ///   重写当前线程的 CurrentUICulture 属性。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 Any 的本地化字符串。
        /// </summary>
        internal static string Any {
            get {
                return ResourceManager.GetString("Any", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Welcome To Work Studio 的本地化字符串。
        /// </summary>
        internal static string AppTitle {
            get {
                return ResourceManager.GetString("AppTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Back 的本地化字符串。
        /// </summary>
        internal static string BackString {
            get {
                return ResourceManager.GetString("BackString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Close 的本地化字符串。
        /// </summary>
        internal static string Close {
            get {
                return ResourceManager.GetString("Close", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Email 的本地化字符串。
        /// </summary>
        internal static string Email {
            get {
                return ResourceManager.GetString("Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Invalid Return Date 的本地化字符串。
        /// </summary>
        internal static string ErrDstDate {
            get {
                return ResourceManager.GetString("ErrDstDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Export 的本地化字符串。
        /// </summary>
        internal static string Export {
            get {
                return ResourceManager.GetString("Export", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Flights 的本地化字符串。
        /// </summary>
        internal static string Flights {
            get {
                return ResourceManager.GetString("Flights", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Home 的本地化字符串。
        /// </summary>
        internal static string HomeString {
            get {
                return ResourceManager.GetString("HomeString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Invoice 的本地化字符串。
        /// </summary>
        internal static string InvoiceString {
            get {
                return ResourceManager.GetString("InvoiceString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Logout 的本地化字符串。
        /// </summary>
        internal static string LogoutString {
            get {
                return ResourceManager.GetString("LogoutString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Please Login Again!  的本地化字符串。
        /// </summary>
        internal static string msgOvertime {
            get {
                return ResourceManager.GetString("msgOvertime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 My Account 的本地化字符串。
        /// </summary>
        internal static string MyAccountString {
            get {
                return ResourceManager.GetString("MyAccountString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Record not found! 的本地化字符串。
        /// </summary>
        internal static string RcdNotFnd {
            get {
                return ResourceManager.GetString("RcdNotFnd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 (&lt;font color=&quot;red&quot;&gt;{0}&lt;/font&gt; Records Found) 的本地化字符串。
        /// </summary>
        internal static string RecordsFoundString {
            get {
                return ResourceManager.GetString("RecordsFoundString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Report 的本地化字符串。
        /// </summary>
        internal static string ReportString {
            get {
                return ResourceManager.GetString("ReportString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 &lt;div class=&quot;line&quot;&gt;
        ///        &lt;/div&gt;
        ///        &lt;div&gt;
        ///            Fields marked with an asterisk (&lt;span style=&quot;color: Red;&quot;&gt;*&lt;/span&gt;) are required.
        ///&lt;/div&gt; 的本地化字符串。
        /// </summary>
        internal static string ReqiureFiledTip {
            get {
                return ResourceManager.GetString("ReqiureFiledTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Request 的本地化字符串。
        /// </summary>
        internal static string Request {
            get {
                return ResourceManager.GetString("Request", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Reset 的本地化字符串。
        /// </summary>
        internal static string Reset {
            get {
                return ResourceManager.GetString("Reset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Return 的本地化字符串。
        /// </summary>
        internal static string Return {
            get {
                return ResourceManager.GetString("Return", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Search 的本地化字符串。
        /// </summary>
        internal static string SearchString {
            get {
                return ResourceManager.GetString("SearchString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Select a format 的本地化字符串。
        /// </summary>
        internal static string SelectFormat {
            get {
                return ResourceManager.GetString("SelectFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 We can not find any results for &apos;{0}&apos;. 的本地化字符串。
        /// </summary>
        internal static string SGNotFound {
            get {
                return ResourceManager.GetString("SGNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 &lt;b&gt;Show {0} Record In A Page&lt;/b&gt; 的本地化字符串。
        /// </summary>
        internal static string ShowString {
            get {
                return ResourceManager.GetString("ShowString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Submit 的本地化字符串。
        /// </summary>
        internal static string Submit {
            get {
                return ResourceManager.GetString("Submit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 To 的本地化字符串。
        /// </summary>
        internal static string To {
            get {
                return ResourceManager.GetString("To", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Excel 的本地化字符串。
        /// </summary>
        internal static string ToExcel {
            get {
                return ResourceManager.GetString("ToExcel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Image 的本地化字符串。
        /// </summary>
        internal static string ToImg {
            get {
                return ResourceManager.GetString("ToImg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Acrobat (PDF) file 的本地化字符串。
        /// </summary>
        internal static string ToPDF {
            get {
                return ResourceManager.GetString("ToPDF", resourceCulture);
            }
        }
    }
}
